version: "3.8"

services:
  db:
    image: postgres:17
    container_name: jira_postgres
    restart: always
    environment:
      POSTGRES_DB: jira
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: jira_app
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    expose:
      - "8080"

  nginx:
    image: nginx:stable-alpine
    container_name: jira_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./resources:/opt/jirarush/resources:ro
    depends_on:
      - app

volumes:
  db_data:
